---
title: "RCoding"
author: "Oleg Sechovcov"
date: "2024-09-09"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

# Data sets

IRIS, MPG

```{r}
head(iris, 5)
nrow(iris)
```

```{r}
head(mpg,5)
nrow(mpg)
```
# SCatter plot

```{r}
ggplot(data = iris) + 
  geom_point(mapping = aes(x = Petal.Length, y = Petal.Width, color = Species)) + 
  labs(x = 'Petal Lenght[cm]', y = 'Petal width [cm]',
       color = 'Iris Species',
       title = 'Iris flowers - Petal Length vs Petal width',
       subtitle = 'Colored by species')
```
```{r}
ggplot(data = iris) + 
  geom_point(mapping = aes(x = Petal.Length, y = Petal.Width, 
                          color = Species))+
                          #size = Species,
                          # shape = Species)) + 
  labs(x = 'Petal Lenght[cm]', y = 'Petal width [cm]',
       size = 'Iris Species',
       title = 'Iris flowers - Petal Length vs Petal width',
       subtitle = 'Colored by species') +
 coord_fixed(ratio = 1)
```
```{r}
ggplot(data = iris) + 
  geom_point(mapping = aes(x = Petal.Length, y = Petal.Width, 
                          color = Species))+
                          #size = Species,
                          # shape = Species)) + 
  labs(x = 'Petal Lenght[cm]', y = 'Petal width [cm]',
       size = 'Iris Species',
       title = 'Iris flowers - Petal Length vs Petal width',
       subtitle = 'Colored by species') +
 coord_fixed(ratio = 1) +
  geom_smooth(mapping = aes(x = Petal.Length, y = Petal.Width), method = lm)
```
```{r}
ggplot(data = iris) + 
  geom_point(mapping = aes(x = Petal.Length, y = Petal.Width, 
                          color = Species))+
  geom_smooth(mapping = aes(x = Petal.Length, y = Petal.Width), method = lm) +
 geom_smooth(mapping = aes(x = Petal.Length, y = Petal.Width, color = Species), method = lm)
```
#Facet wrap and facet grid
```{r}
ggplot(data = iris) + 
  geom_point(mapping = aes(x = Petal.Length, y = Petal.Width)) + 
  facet_wrap(~Species)
```
#Box plots
```{r}
ggplot(data = iris) + geom_boxplot(mapping = aes(y = Species, x = Petal.Length, fill = Species), alpha = 0.2,
                                   color = 'darkred')+
  labs(x = 'Petal Lenght [cm]',
       y= 'Iris Species')
```

```{r}
ggplot(data = mpg) + geom_boxplot(mapping = aes(x = class, y = hwy, fill = class), show.legend = FALSE, alpha = 0.2,
                                   color = 'darkred')
 
```
# Histogram and Denisty Plot

```{r}
ggplot(iris) + geom_histogram(aes(x = Petal.Length, color = Species), binwidth = 0.3, position = 'dodge')
```

```{r}
versicolor <- filter(iris, Species == 'versicolor')
```
```{r}
ggplot(versicolor) + geom_histogram(aes(x= Petal.Length), color = 'Black', fill = 'limegreen', binwidth = 0.1)
```
```{r}
ggplot(versicolor) +
  geom_density(aes(x = Petal.Length), fill = 'red', alpha = 0.3, color = 'yellow', size = 2)
```
```{r}
ggplot(versicolor) +
  geom_histogram(aes(x = Petal.Length, y = after_stat(density)), fill = 'limegreen', binwidth = 0.1)+
  geom_density(aes(x = Petal.Length), color = 'red', fill = 'yellow' , alpha = 0.3)
```

```{r}
ggplot(iris) + 
geom_density(aes(x = Petal.Length, fill = Species), alpha = 0.3)
```
```{r}
ggplot(iris) + 
geom_density(aes(x = Petal.Length, fill = Species), alpha = 0.3) +
geom_histogram(aes(x = Petal.Length, y = after_stat(density), fill = Species), alpha = 0.3)
```
# Empirical cumulative distribution function - stat_ecdf
```{r}
ggplot(iris) + 
  stat_ecdf(mapping = aes(x = Sepal.Length, color = Species))
```
# Barplots
```{r}
ggplot(mpg) +
  geom_bar(mapping = aes(x = class, fill = manufacturer), color = 'black')
```
```{r}
library(viridis)
```


```{r}
ggplot(mpg) +
  geom_bar(mapping = aes(x = class, fill = manufacturer), color = 'black') +
  scale_fill_viridis(discrete = TRUE)
```
```{r}
ggplot(mpg) +
  geom_bar(mapping = aes(x = manufacturer, fill = class), color = 'black') +
  scale_fill_brewer(palette = 'Spectral') +
  coord_flip()
```




