---
title: "Tidy Data and Data Conversion"
author: "Oleg Sechovcov"
date: "2024-11-04"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
```

# Gather and spread commands

```{r}
wide_data <- tribble(
  ~country,  ~price2000, ~price2005, ~price2010, ~price2015,
  'Germany', 1001, 2001,1500,1700,
  'Denmark', 1100, 2000,1600,1800,
  'France', 999, 2000, 1550, 1820,
  'Austria', 1010, 2000, 1500, 1700, 
  'UK', 1050, 1950, 1600, 1200,
  'Norway', 1150, 2050, 1599, 1600,
  'Poland', 900, 1500, 1000, 1500,
)
```

```{r}
wide_data %>% gather(year, price, -country)
```

```{r}
wide_data %>% gather(year, price, -country) %>% spread(year, price)
```
```{r}
long_data <- wide_data %>% gather(year, price, price2000:price2015)
```

```{r}
ggplot(long_data)+
  geom_point(aes(x = year, y = price, color = country))
```
```{r}
long_data %>% spread(year, price)
```
```{r}
ggplot(wide_data)+
  geom_bar(aes(x = country, y = price2010, fill = country), stat = 'identity')
```
```{r}
long_data %>% 
  filter(year == 'price2010') %>%
  ggplot()+
  geom_bar(aes(x = country, y = price, fill = country), stat = 'identity')
```
# Joins

```{r}
library(gapminder)
```


```{r}
gapminder
```

```{r}
country_population <- gapminder %>% filter(year == 1987) %>%  select(country, pop)
```
```{r}
country_continent <- gapminder %>% select(country, continent) %>%  unique()
```

```{r}
country_population %>% left_join(country_continent, by = 'country')
```
```{r}
country_population %>% left_join(country_continent, by = c('CTR' = 'country'))
```

# String operations

str_view

```{r}
x <- c('one', 'lamp', 'table', 'tea', 'mug', 'couch', 'candle', 'spring')
```

```{r}
str_view(x, 'e')
```
```{r}
str_view(x, 'c...')
```
```{r}
str_view(x, 'l..p')
```
```{r}
str_view(x, '.n')
```
```{r}
str_view(x, 't.*')
```
```{r}

```



